import Fastify from 'fastify';import cookie from '@fastify/cookie';import cors from '@fastify/cors';import rateLimit from '@fastify/rate-limit';import bcrypt from 'bcryptjs';import {SignJWT,jwtVerify} from 'jose';import {Server} from 'socket.io';import {applyMove,createGame,moveSchema,rematchSchema,type LobbyState,type PlayerId} from '@pai-sho/shared';import {config} from './config.js';import * as db from './store.js';
const app=Fastify({logger:{redact:['req.headers.cookie','req.headers.authorization','body.password']}});const key=new TextEncoder().encode(config.JWT_SECRET);const sessions=new Map<PlayerId,string>();
await app.register(cors,{origin:config.NODE_ENV==='development'?[config.FRONTEND_URL,'http://localhost:3000']:config.FRONTEND_URL,credentials:true});await app.register(cookie);await app.register(rateLimit,{global:false});
async function token(id:PlayerId,session:string){return new SignJWT({id,session}).setProtectedHeader({alg:'HS256'}).setIssuedAt().setExpirationTime('12h').sign(key)}
async function identity(raw?:string){if(!raw)return null;try{const {payload}=await jwtVerify(raw,key);const id=payload.id as PlayerId,session=payload.session as string;return sessions.get(id)===session?id:null}catch{return null}}
app.decorateRequest('player',null);app.addHook('preHandler',async(req)=>{(req as typeof req&{player:PlayerId|null}).player=await identity(req.cookies.paisho_session)});
app.get('/health',async()=>({status:'ok'}));
app.post('/auth/login',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(req,reply)=>{const body=req.body as {username?:string,password?:string};const accounts=[{id:'one' as const,u:config.PLAYER_ONE_USERNAME,h:config.PLAYER_ONE_PASSWORD_HASH},{id:'two' as const,u:config.PLAYER_TWO_USERNAME,h:config.PLAYER_TWO_PASSWORD_HASH}];const account=accounts.find(a=>a.u===body.username);if(!account||!body.password||!await bcrypt.compare(body.password,account.h))return reply.code(401).send({error:'Неправильне ім’я або пароль'});if(sessions.has(account.id))return reply.code(409).send({error:'Цей акаунт уже має активну сесію'});const session=crypto.randomUUID();sessions.set(account.id,session);reply.setCookie('paisho_session',await token(account.id,session),{httpOnly:true,secure:config.NODE_ENV==='production',sameSite:config.NODE_ENV==='production'?'none':'lax',path:'/',maxAge:43200});return{id:account.id,name:account.u}});
app.post('/auth/logout',async(req,reply)=>{const p=(req as typeof req&{player:PlayerId|null}).player;if(p)sessions.delete(p);reply.clearCookie('paisho_session',{path:'/'});return{ok:true}});app.get('/auth/me',async(req,reply)=>{const p=(req as typeof req&{player:PlayerId|null}).player;return p?{id:p,name:p==='one'?config.PLAYER_ONE_USERNAME:config.PLAYER_TWO_USERNAME}:reply.code(401).send({error:'unauthorized'})});
const lobby:LobbyState={players:{one:{id:'one',name:config.PLAYER_ONE_USERNAME,side:'host',online:false,ready:false},two:{id:'two',name:config.PLAYER_TWO_USERNAME,side:'guest',online:false,ready:false}},currentGameId:null};
function auth(req:any,reply:any){if(!req.player)return reply.code(401).send({error:'unauthorized'})}app.get('/lobby',{preHandler:auth},async()=>lobby);app.get('/games/current',{preHandler:auth},async()=>await db.current());app.get('/games/:id',{preHandler:auth},async req=>await db.find((req.params as {id:string}).id));app.get('/games/:id/moves',{preHandler:auth},async req=>(await db.find((req.params as {id:string}).id))?.moves??[]);
const io=new Server(app.server,{cors:{origin:config.NODE_ENV==='development'?[config.FRONTEND_URL,'http://localhost:3000']:config.FRONTEND_URL,credentials:true}});io.use(async(socket,next)=>{const raw=socket.request.headers.cookie?.match(/paisho_session=([^;]+)/)?.[1];const p=await identity(raw);if(!p)return next(new Error('unauthorized'));socket.data.player=p;next()});
io.on('connection',socket=>{const p=socket.data.player as PlayerId;lobby.players[p].online=true;socket.join('lobby');io.to('lobby').emit('lobby:state',lobby);void db.current().then(g=>g&&socket.emit('game:state',g));socket.on('lobby:join',()=>{socket.emit('lobby:state',lobby);void db.current().then(g=>g&&socket.emit('game:state',g))});const ready=async(v:boolean)=>{lobby.players[p].ready=v;io.emit('lobby:state',lobby);if(lobby.players.one.ready&&lobby.players.two.ready&&!await db.current()){const game=await db.create(createGame(lobby.players));lobby.currentGameId=game.id;lobby.players.one.ready=lobby.players.two.ready=false;io.emit('game:started',game)}};socket.on('player:ready',()=>void ready(true));socket.on('player:unready',()=>void ready(false));socket.on('game:move',async raw=>{const parsed=moveSchema.safeParse(raw);if(!parsed.success)return socket.emit('game:move_rejected',{commandId:raw?.commandId??'',reason:'Некоректна команда'});try{const game=await db.current();if(!game)throw new Error('Активну гру не знайдено');const next=applyMove(game,p,parsed.data);await db.update(next,game.version,parsed.data.commandId);io.emit('game:state',next);if(next.result)io.emit('game:finished',next.result)}catch(e){socket.emit('game:move_rejected',{commandId:parsed.data.commandId,reason:e instanceof Error?e.message:'Хід відхилено'})}});socket.on('game:resign',v=>socket.emit('game:move',{...v,kind:'resign'}));socket.on('game:rematch',async raw=>{const parsed=rematchSchema.safeParse(raw);if(!parsed.success)return;const g=await db.find(parsed.data.gameId);if(!g||g.phase!=='finished')return;g.rematch[p]=true;await db.update(g,g.version,crypto.randomUUID());if(g.rematch.one&&g.rematch.two){const n=await db.create(createGame(lobby.players));io.emit('game:started',n)}else io.emit('game:state',g)});socket.on('disconnect',()=>{lobby.players[p].online=false;lobby.players[p].ready=false;io.emit('lobby:state',lobby)})});
await db.migrate();await app.listen({port:config.PORT,host:'0.0.0.0'});
