import type {BoardPoint,GameResult,GameState,Harmony,Move,PlayerId,Tile,TileType} from './types.js';
export class RuleError extends Error{}
const radius=8;
export const points:BoardPoint[]=[];
for(let x=-radius;x<=radius;x++)for(let y=-radius;y<=radius;y++){if(x*x+y*y>72)continue;const gate=(x===0&&Math.abs(y)===8)||(y===0&&Math.abs(x)===8);const garden=gate?'gate':x===0||y===0?'neutral':(x*y>0?'red':'white');points.push({id:`${x},${y}`,x,y,gate,garden,midline:x===0||y===0});}
export const pointMap=new Map(points.map(p=>[p.id,p]));
export const BASIC:TileType[]=['rose','chrysanthemum','rhododendron','jasmine','lily','whiteJade'];
export const RED=new Set<TileType>(['rose','chrysanthemum','rhododendron']);
export const WHITE=new Set<TileType>(['jasmine','lily','whiteJade']);
export const RANGE:Record<TileType,number>={rose:3,chrysanthemum:3,rhododendron:4,jasmine:3,lily:3,whiteJade:4,knotweed:2,rock:1,wheel:1,boat:1,whiteLotus:2,orchid:6};
export const HARMONY:Record<string,TileType[]>={rose:['whiteJade'],chrysanthemum:['jasmine'],rhododendron:['lily'],jasmine:['chrysanthemum'],lily:['rhododendron'],whiteJade:['rose'],whiteLotus:BASIC};
export const CLASH:Record<string,TileType[]>={rose:['jasmine'],chrysanthemum:['lily'],rhododendron:['whiteJade'],jasmine:['rose'],lily:['chrysanthemum'],whiteJade:['rhododendron']};
const pos=(t:Tile)=>t.position&&pointMap.get(t.position);
export function path(from:BoardPoint,to:BoardPoint){const dx=to.x-from.x,dy=to.y-from.y;if(dx!==0&&dy!==0&&Math.abs(dx)!==Math.abs(dy))return [];const n=Math.max(Math.abs(dx),Math.abs(dy));return Array.from({length:n},(_,i)=>pointMap.get(`${from.x+dx/n*(i+1)},${from.y+dy/n*(i+1)}`)).filter(Boolean) as BoardPoint[]}
export function canOccupy(t:Tile,p:BoardPoint){if(t.kind!=='basic')return true;if(RED.has(t.type))return p.garden!=='white';if(WHITE.has(t.type))return p.garden!=='red';return true}
export function legalTargets(s:GameState,tileId:string):string[]{const t=[...s.board,...s.reserves.one,...s.reserves.two].find(v=>v.id===tileId);if(!t)return[];if(!t.position)return points.filter(p=>p.gate&&!s.board.some(b=>b.position===p.id)&&canOccupy(t,p)).map(p=>p.id);const a=pos(t)!;return points.filter(b=>{const route=path(a,b);if(!route.length||route.length>RANGE[t.type]||!canOccupy(t,b))return false;const destination=s.board.find(v=>v.position===b.id);if(destination&&!CLASH[t.type]?.includes(destination.type))return false;return route.slice(0,-1).every(p=>!s.board.some(v=>v.position===p.id))}).map(p=>p.id)}
export function calculateHarmonies(board:Tile[]):Harmony[]{const result:Harmony[]=[];for(let i=0;i<board.length;i++)for(let j=i+1;j<board.length;j++){const a=board[i]!,b=board[j]!,pa=pos(a),pb=pos(b);if(!pa||!pb||a.owner!==b.owner||!a.blooming||!b.blooming)continue;if(!HARMONY[a.type]?.includes(b.type)&&!HARMONY[b.type]?.includes(a.type))continue;if((pa.x===pb.x||pa.y===pb.y)&&!board.some(t=>t!==a&&t!==b&&t.position&&path(pa,pb).slice(0,-1).some(p=>p.id===t.position)))result.push({a:a.id,b:b.id,midline:(pa.x*pb.x<0)||(pa.y*pb.y<0)});}return result}
export function applyMove(state:GameState,player:PlayerId,move:Move):GameState{if(state.phase!=='playing')throw new RuleError('Партія не активна');if(player!==state.activePlayer)throw new RuleError('Зараз хід суперника');if(state.moves.some(m=>m.move.commandId===move.commandId))return state;if(move.kind==='resign')return finish(state,{winner:player==='one'?'two':'one',reason:'resignation'},player,move);if(!move.tileId||!move.to)throw new RuleError('Оберіть плитку та ціль');const own=[...state.board,...state.reserves[player]].find(t=>t.id===move.tileId&&t.owner===player);if(!own)throw new RuleError('Ця плитка вам не належить');if(!legalTargets(state,own.id).includes(move.to))throw new RuleError('Недозволена ціль або шлях заблокований');const next=structuredClone(state);let tile=next.board.find(t=>t.id===own.id);if(!tile){const ix=next.reserves[player].findIndex(t=>t.id===own.id);tile=next.reserves[player].splice(ix,1)[0]!;next.board.push(tile)}const captured=next.board.find(t=>t.position===move.to);if(captured)next.board=next.board.filter(t=>t.id!==captured.id);tile.position=move.to;tile.blooming=!pointMap.get(move.to)!.gate;next.lastMove=move;next.turn++;next.activePlayer=player==='one'?'two':'one';next.harmonies=calculateHarmonies(next.board);next.version++;next.updatedAt=new Date().toISOString();next.moves.push({turn:next.turn-1,player,move,at:next.updatedAt,notation:`${move.kind} ${tile.type} → ${move.to}`});const ownerLinks=next.harmonies.filter(h=>next.board.find(t=>t.id===h.a)?.owner===player);if(formsRing(ownerLinks,next.board))return finish(next,{winner:player,reason:'harmony-ring'},player,move);if(next.reserves.one.filter(t=>t.kind==='basic').length+next.reserves.two.filter(t=>t.kind==='basic').length===0){const one=next.harmonies.filter(h=>h.midline&&next.board.find(t=>t.id===h.a)?.owner==='one').length,two=next.harmonies.filter(h=>h.midline&&next.board.find(t=>t.id===h.a)?.owner==='two').length;return finish(next,{winner:one===two?null:one>two?'one':'two',reason:one===two?'draw':'last-basic'},player,move)}if(!hasAnyMove(next,next.activePlayer))throw new RuleError('Хід заборонено: суперник не матиме жодного ходу');return next}
function formsRing(h:Harmony[],b:Tile[]){if(h.length<3)return false;const graph=new Map<string,string[]>();h.forEach(e=>{graph.set(e.a,[...(graph.get(e.a)||[]),e.b]);graph.set(e.b,[...(graph.get(e.b)||[]),e.a])});return [...graph.values()].some(v=>v.length>=2)&&[...graph.keys()].every(id=>b.some(t=>t.id===id))&&h.length>=[...graph.keys()].length}
function hasAnyMove(s:GameState,p:PlayerId){return [...s.board.filter(t=>t.owner===p),...s.reserves[p]].some(t=>legalTargets(s,t.id).length)}
function finish(s:GameState,result:GameResult,p:PlayerId,m:Move){const n=structuredClone(s);n.phase='finished';n.result=result;n.updatedAt=new Date().toISOString();if(m.kind==='resign')n.moves.push({turn:n.turn,player:p,move:m,at:n.updatedAt,notation:'Здача'});return n}
