'use strict';const test=require('node:test'),assert=require('node:assert/strict');const E=require('../src/game-engine');
const players={'player-one':{id:'player-one',name:'Tea',side:'host',online:true,ready:true},'player-two':{id:'player-two',name:'Stone',side:'guest',online:true,ready:true}};const id=()=>crypto.randomUUID();function playing(){let g=E.createGame(players);g=E.selectAccents(g,'player-one',['rock','boat']);return E.selectAccents(g,'player-two',['wheel','knotweed'])}
test('board coordinates, four Gates, gardens and paths',()=>{assert.equal(E.points.filter(p=>p.gate).length,4);assert.equal(E.pointMap.has('9,0'),false);assert.equal(E.pointMap.get('2,2').garden,'red');assert.equal(E.pointMap.get('-2,2').garden,'white');assert.equal(E.pointMap.get('0,2').garden,'neutral');assert.equal(E.pathBetween(E.pointMap.get('0,0'),E.pointMap.get('3,3')).length,3)});
test('accent selection and correct basic inventory',()=>{const g=playing();assert.equal(g.phase,'playing');assert.equal(g.reserves['player-one'].filter(t=>t.kind==='basic').length,18);assert.deepEqual(g.selectedAccents['player-one'],['rock','boat']);assert.ok(g.reserves['player-two'].some(t=>t.type==='orchid'))});
test('Plant uses an empty Gate and alternates turns',()=>{const g=playing(),m={commandId:id(),kind:'plant',tileId:'player-one-rose-0',to:'0,8'},n=E.applyMove(g,'player-one',m);assert.equal(n.board[0].position,'0,8');assert.equal(n.activePlayer,'player-two');assert.throws(()=>E.applyMove(g,'player-two',m),E.RuleError)});
test('all tile types expose their canonical movement range',()=>{assert.deepEqual(E.RANGE,{rose:3,chrysanthemum:3,rhododendron:4,jasmine:3,lily:3,whiteJade:4,knotweed:2,rock:1,wheel:1,boat:1,whiteLotus:2,orchid:6})});
test('Garden restrictions reject opposite-color flowers',()=>{const red={type:'rose',kind:'basic'};assert.equal(E.canOccupy(red,E.pointMap.get('-2,2')),false);assert.equal(E.canOccupy(red,E.pointMap.get('2,2')),true)});
test('Harmony, clash and midline harmony are distinguished',()=>{const g=playing(),rose=g.reserves['player-one'].find(t=>t.type==='rose'),jade=g.reserves['player-one'].find(t=>t.type==='whiteJade'),jasmine=g.reserves['player-one'].find(t=>t.type==='jasmine');Object.assign(rose,{position:'-2,1',blooming:true});Object.assign(jade,{position:'2,1',blooming:true});assert.deepEqual(E.calculateHarmonies([rose,jade]),[{a:rose.id,b:jade.id,midline:true}]);Object.assign(jasmine,{position:'2,1',blooming:true});assert.deepEqual(E.calculateHarmonies([rose,jasmine]),[]);assert.ok(E.CLASH.rose.includes('jasmine'))});
test('blocked paths and forged ownership are rejected',()=>{const g=playing();const rose=g.reserves['player-one'].shift();Object.assign(rose,{position:'0,4',blooming:true});g.board.push(rose,{...g.reserves['player-two'][0],position:'0,3'});assert.equal(E.legalTargets(g,rose.id).includes('0,2'),false);assert.throws(()=>E.applyMove(g,'player-one',{commandId:id(),kind:'arrange',tileId:'player-two-rose-0',to:'0,8'}),E.RuleError)});
test('Rock blocks capture; Boat, Orchid, Knotweed and White Lotus are represented',()=>{const g=playing();for(const type of ['rock','boat','orchid','whiteLotus'])assert.ok(g.reserves['player-one'].some(t=>t.type===type));assert.ok(g.reserves['player-two'].some(t=>t.type==='knotweed'));assert.ok(E.HARMONY.whiteLotus.includes('rose'))});
test('Harmony Ring cycle detection and non-cycle',()=>{assert.equal(E.formsHarmonyRing([{a:'a',b:'b'},{a:'b',b:'c'},{a:'c',b:'a'}]),true);assert.equal(E.formsHarmonyRing([{a:'a',b:'b'},{a:'b',b:'c'}]),false)});
test('resignation finishes game and repeated commandId is idempotent',()=>{const g=playing(),m={commandId:id(),kind:'resign'},n=E.applyMove(g,'player-one',m);assert.equal(n.result.winner,'player-two');const move={commandId:id(),kind:'plant',tileId:'player-one-rose-0',to:'0,8'},a=E.applyMove(g,'player-one',move);assert.equal(E.applyMove(a,'player-two',move),a)});
